export const colorToken = {
  amber50: "#fffbeb",
  amber200: "#fde68a",
  amber700: "#a16207",
  blue50: "#eff6ff",
  blue100: "#dbeafe",
  blue300: "#93c5fd",
  blue500: "#3b82f6",
  blue600: "#2563eb",
  blue700: "#1d4ed8",
  cyan400: "#22d3ee",
  emerald50: "#ecfdf5",
  emerald400: "#34d399",
  emerald700: "#047857",
  neutral25: "#fdfcfb",
  neutral50: "#faf9f7",
  neutral100: "#f4f2ef",
  neutral150: "#ece9e5",
  neutral200: "#e4e0db",
  neutral300: "#d3cec7",
  neutral400: "#a9a29a",
  neutral500: "#77716a",
  neutral600: "#57524c",
  neutral700: "#3f3b37",
  neutral800: "#292724",
  neutral850: "#211f1d",
  neutral900: "#191816",
  neutral950: "#11100f",
  red50: "#fef2f2",
  red300: "#fca5a5",
  red600: "#dc2626",
  red700: "#b91c1c",
  white: "#ffffff",
} as const

export const colorPaletteContract = {
  accent: {
    foreground: null,
    solid: null,
    subtle: null,
  },
  background: {
    canvas: null,
    card: null,
    elevated: null,
    overlay: null,
    subtle: null,
    sunken: null,
  },
  border: {
    default: null,
    interactive: null,
    strong: null,
    subtle: null,
  },
  focus: null,
  icon: {
    default: null,
    muted: null,
  },
  intent: {
    danger: {
      background: null,
      foreground: null,
      subtle: null,
    },
    primary: {
      active: null,
      background: null,
      foreground: null,
      hover: null,
    },
    success: {
      background: null,
      foreground: null,
      subtle: null,
    },
    warning: {
      background: null,
      foreground: null,
      subtle: null,
    },
  },
  text: {
    danger: null,
    inverse: null,
    link: null,
    muted: null,
    primary: null,
    secondary: null,
    success: null,
    warning: null,
  },
}

export const lightColorPalette = {
  accent: {
    foreground: colorToken.blue700,
    solid: colorToken.blue600,
    subtle: colorToken.blue50,
  },
  background: {
    canvas: colorToken.neutral50,
    card: colorToken.white,
    elevated: colorToken.white,
    overlay: "rgb(17 16 15 / 0.56)",
    subtle: colorToken.neutral100,
    sunken: colorToken.neutral25,
  },
  border: {
    default: colorToken.neutral200,
    interactive: colorToken.neutral300,
    strong: colorToken.neutral400,
    subtle: "rgb(87 82 76 / 0.13)",
  },
  focus: colorToken.blue500,
  icon: {
    default: colorToken.neutral700,
    muted: colorToken.neutral500,
  },
  intent: {
    danger: {
      background: colorToken.red600,
      foreground: colorToken.white,
      subtle: colorToken.red50,
    },
    primary: {
      active: colorToken.blue700,
      background: colorToken.blue600,
      foreground: colorToken.white,
      hover: colorToken.blue700,
    },
    success: {
      background: colorToken.emerald700,
      foreground: colorToken.white,
      subtle: colorToken.emerald50,
    },
    warning: {
      background: colorToken.amber700,
      foreground: colorToken.white,
      subtle: colorToken.amber50,
    },
  },
  text: {
    danger: colorToken.red700,
    inverse: colorToken.white,
    link: colorToken.blue700,
    muted: colorToken.neutral500,
    primary: colorToken.neutral950,
    secondary: colorToken.neutral600,
    success: colorToken.emerald700,
    warning: colorToken.amber700,
  },
} as const

export const darkColorPalette = {
  accent: {
    foreground: colorToken.blue300,
    solid: colorToken.blue500,
    subtle: "rgb(59 130 246 / 0.14)",
  },
  background: {
    canvas: colorToken.neutral950,
    card: colorToken.neutral900,
    elevated: colorToken.neutral850,
    overlay: "rgb(0 0 0 / 0.74)",
    subtle: colorToken.neutral800,
    sunken: "#0c0b0a",
  },
  border: {
    default: colorToken.neutral800,
    interactive: colorToken.neutral700,
    strong: colorToken.neutral600,
    subtle: "rgb(211 206 199 / 0.1)",
  },
  focus: colorToken.blue300,
  icon: {
    default: colorToken.neutral300,
    muted: colorToken.neutral500,
  },
  intent: {
    danger: {
      background: colorToken.red700,
      foreground: colorToken.white,
      subtle: "rgb(220 38 38 / 0.14)",
    },
    primary: {
      active: colorToken.blue700,
      background: colorToken.blue600,
      foreground: colorToken.white,
      hover: colorToken.blue500,
    },
    success: {
      background: colorToken.emerald700,
      foreground: colorToken.white,
      subtle: "rgb(52 211 153 / 0.12)",
    },
    warning: {
      background: colorToken.amber700,
      foreground: colorToken.white,
      subtle: "rgb(253 230 138 / 0.1)",
    },
  },
  text: {
    danger: colorToken.red300,
    inverse: colorToken.neutral950,
    link: colorToken.blue300,
    muted: colorToken.neutral400,
    primary: colorToken.neutral50,
    secondary: colorToken.neutral300,
    success: colorToken.emerald400,
    warning: colorToken.amber200,
  },
} as const
